/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.0.3-27-gb865754e49"
#endif /* AVUTIL_FFVERSION_H */
