/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.1.1-8-gb21e00eda5b"
#endif /* AVUTIL_FFVERSION_H */
